name: Build and publish

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  workflow_dispatch:

# Ensure token has rights to write packages
permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 'php8.1-apache', 'php7.4-apache' ]
        suitecrm: [ 'latest', '7.12.7' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login to GHCR using the automatically-provided token
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Optional: Docker Hub login (uncomment if you want to push to Docker Hub)
      # - name: Login to DockerHub
      #   if: secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_TOKEN != ''
      #   uses: docker/login-action@v2
      #   with:
      #     registry: docker.io
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: variants/${{ matrix.php }}/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/suitecrm:${{ matrix.suitecrm }}-${{ matrix.php }}
            ghcr.io/${{ github.repository_owner }}/suitecrm:${{ matrix.suitecrm }}
          build-args: |
            SUITECRM_VERSION=${{ matrix.suitecrm }}

      - name: Create GitHub Release (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref }}
          files: |
            README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

